/* istanbul ignore file */
export const routes = {
  index: '/',
  auth: {
    index: '/auth',
    signup: '/auth/signup',
    signin: '/auth/signin',
    reset: '/auth/reset',
    recover: '/auth/recover',
  },
  dashboard: {
    index: '/dashboard',
    analytics: '/dashboard/analytics',
    contact: '/dashboard/contact',
    events: {
      list: '/dashboard/events',
      edit: '/dashboard/events/:id/edit',
      getEdit: (id: string) => `/dashboard/events/${id}/edit`,
      editProfile: '/dashboard/events/:id/edit/profile',
      getEditProfile: (id: string) => `/dashboard/events/${id}/edit/profile`,
      editSessions: '/dashboard/events/:id/edit/sessions',
      getEditSessions: (id: string) => `/dashboard/events/${id}/edit/sessions`,
      editSettings: '/dashboard/events/:id/edit/settings',
      getEditSettings: (id: string) => `/dashboard/events/${id}/edit/settings`,
      editRegistration: '/dashboard/events/:id/edit/registration',
      getEditRegistration: (id: string) => `/dashboard/events/${id}/edit/registration`,
      editSponsors: '/dashboard/events/:id/edit/sponsors',
      getEditSponsors: (id: string) => `/dashboard/events/${id}/edit/sponsors`,
    },
    notes: '/dashboard/notes',
    profile: '/dashboard/profile',
    support: '/dashboard/support',
    users: '/dashboard/users',
    setupSession: '/dashboard/setup-session',
    onboarding: {
      index: '/dashboard/onboarding',
      profile: '/dashboard/onboarding/profile',
      team: '/dashboard/onboarding/team',
      theme: '/dashboard/onboarding/theme',
      event: '/dashboard/onboarding/event',
    },
  },
  paywall: {
    plans: '/paywall/plans',
    pay: '/paywall/pay',
  },
  terms: '/terms',
  policy: '/policy',
  faq: '/faq',
};
