name: Deploy

on:
  push:
    branches:
      - 'develop'
      - 'release/*'
      - 'beta'
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Env: set package version"
        run: >
          echo "APP_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",\t ]//g')" >> $GITHUB_ENV
      - name: "Env: setup DEV enviroment"
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          cat .env.dev > .env
          cat .env >> $GITHUB_ENV
      - name: "Env: setup QA enviroment"
        if: ${{ startsWith(github.ref, 'refs/heads/release') }}
        run: |
          cat .env.qa > .env
          cat .env >> $GITHUB_ENV
      - name: "Env: setup BETA enviroment"
        if: ${{ github.ref == 'refs/heads/beta' }}
        run: |
          cat .env.beta > .env
          cat .env >> $GITHUB_ENV
      - name: "Env: setup PRD enviroment"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          cat .env.prd > .env
          cat .env >> $GITHUB_ENV
      - name: "AWS: Configure"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: "Yarn: install"
        run: yarn install
      - name: "Yarn: lint"
        run: |
          yarn lint
      - name: "Yarn: dist"
        run: yarn dist
      - name: "AWS: Deploy"
        run: |
          aws s3 sync --acl public-read --follow-symlinks --delete ./dist s3://$AWS_S3_BUCKET
