name: Lint
on:
  push:
    paths:
      - src/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn lint
      - run: yarn test
